
#Trigger of the Pipeline
on:
  # Initiate the Pipeline when there's a Push Event in the Main Branch
  push:
    branches:
      - main

jobs:

  # Stage 1
  # Place to add name, short and descriptive
  build-docker-image:
    # Or here
    name: The job to build the application docker image.
    # runs-on: csd-windows-local!
    runs-on: aws-debian-runner-1 # Using a self-hosted runner
    #The instructions are defined as steps
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2 # A GitHub action for a predefined job that clones the project into the workdir.
      - name: Build Docker Image
        run: docker build -t flask-app-1:v1.0.0 -f Dockerfile .

  test:
    name: Unit testing of the application
    needs: [build-docker-image]
    # runs-on: csd-windows-local
    runs-on: aws-debian-runner-1
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2 # A GitHub action for a predefined job that clones the project into the workdir.
      - name: Set up a virtual environment
        run: |
          python3 -m venv venv # Create a virtual environment in  directory called venv.
          venv/bin/activate
          pip install flask
          pip install pytest
      - name: Run unit tests inside the virtual environment
        run: |
          venv/bin/activate
          pytest tests/ # Run the unit testing files under the directoy tests.

  deploy-docker-image:
    name: Deploy the flask image
    needs: [build-docker-image]
    # runs-on: csd-windows-local
    runs-on: aws-debian-runner-1
    steps:
      - name: Deploy the image
        run: docker run -d -p 5000:5000 flask-app-1:v1.0.0 # -d tag lets us run container in background. Good for a server.


  # Stage 2
  unit-test:
    name: The job to unit test the application docker image.
    # runs-on: csd-windows-local
    runs-on: aws-debian-runner-1
    needs: [build-docker-image] # Wait for last job to finish.
    steps:
      - name: Echo unit testing of the application
        run: echo "Unit test the docker image..."